theme:
    name: material
    color_theme: ff0000
    custom_dir: overrides
    language: en
    logo: assets/img/logo.png
    favicon: assets/img/favicon.ico
    palette:
        - scheme: default
          toggle:
            icon: material/eye
            name: Switch to dark mode
        - scheme: slate
          toggle:
            icon: material/eye-outline
            name: Switch to light mode
    features:
        - header.autohide
        - search.suggest
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.expand
        - navigation.indexes
        - navigation.top
        - navigation.sections
    icon:
        repo: fontawesome/brands/github

plugins:
    - pdf-export:
        enabled_if_env: ENABLE_PDF_EXPORT
    - tags:
        tags_file: tags.md
    - minify:
        minify_html: true
        minify_js: true
        htmlmin_opts:
          remove_comments: true
    - git-revision-date:
        enabled_if_env: CI
    - search:
        lang: en
        prebuild_index: true
    - git-revision-date-localized:
        type: date
        fallback_to_build_date: true
        enable_creation_date: true
    # - macros:
    #     module_name: commands_and_partners
    - mike:
        version_selector: true   
        css_dir: css             
        javascript_dir: js       
        canonical_version: null

site_name: Akatsuki
site_author: Dhruva Shaw
repo_name: Source Code
# site_description: Konichiwa &#128075;, myself Minato Namikaze, Konohagakure Yondaime Hokage. I do every work of a Hokage in a swift and clean way &#9889;
copyright: We are a fan-made organization based on the anime "Naruto", we are in no way associated with Tokyo Tv Corporation.

markdown_extensions:
  - tables
  - smarty
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - toc:
      permalink: true
      toc_depth : 2
      slugify: !!python/name:pymdownx.slugs.uslugify
      title: Category
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: true

extra:
  discord_invite_code: aS2Szp7FEB
  site_keywords: akatsuki, organization, lpu, akatsuki-lpu, naruto, events
  version:
      provider: mike
  analytics:
    provider: google
    property: !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_TOKEN"]

nav:
  - Preamble: index.md
  # - Commands: 
  #   - commands/index.md
  #   - Message Commands List: commands/message_commands.md
  #   - Application Commands List: commands/application_commands.md
  # - Contributors: contributors.md
  # - Rules:
  #   - Privacy Policy: rules/privacy_policy.md
  #   - Terms of Use: rules/terms_of_use.md
  # - Partners: partners.md
  # - Listing: botlist.md
  # - Discord Server: server.md
